dir:
  cor: correct_submissions
  grad: graded_submissions
  out: outputs
  sol: solutions
  sol_out: sol_output
  sub: submissions
  test: tests
editor: atom
methods:
- clean_words
- read_file
- write_file
modify: 1
output_only: false
check_file: true
point_weight: 3
solution_script: Week11-random_file.py
