check_file: true
dir:
  cor: correct_submissions
  grad: graded_submissions
  sub: submissions
  out: outputs
  sol_out: sol_output
  test: tests
  sol: solutions
editor: atom
methods:
- clean_words
- read_file
- write_file
modify: 1
output_only: false
point_weight: 3
solution_script: Week11-random_file.py
